.env.prod.yaml
.env.staging.yaml
.gcloudignore
.travis.yml
deploy/pubsub.sh
functions/__init__.py
functions/settings.py
functions/uploads.py
functions/util.py
main.py
requirements.dev.txt
tests/functions/test_uploads.py
tests/functions/test_util.py
tests/test_main.py
tests/util.py

This PR creates a function that gets triggered by pub/sub events published to the `uploads` topic (this happens following successful upload job completion, due to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/23).

Create + deploy function triggered by upload event

---

functions/uploads.py

The field `DownloadableFiles.trial_id` has a foreign key constraint on `TrialMetadata.trial_id`. In the event that we're ingesting an upload for a trial that doesn't yet exist (i.e., has no entry in the `trial_metadata` table), trying to insert a `DownloadableFiles` record before creating the related `TrialMetadata` record leads to a SQL constraint error.
This PR waits to add `DownloadableFiles` records to the db until after the `TrialMetadata` record has been created (if this is a new trial) or updated (if this is an existing trial) by the `TrialMetadata.patch_trial_metadata` method.

Avoid foreign-key-error on files for a new trial

---

functions/uploads.py
tests/functions/test_uploads.py

see: https://github.com/CIMAC-CIDC/cidc-api-gae/pull/98

Use create_from_blob function for saving assay metadata

---

functions/__init__.py
main.py

fixes bug causing staging deployment to fail.

Add missing generate_csvs exports

---

functions/uploads.py
requirements.txt
tests/functions/test_uploads.py

accompanying changes to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/119 and https://github.com/CIMAC-CIDC/cidc-schemas/pull/195

Save additional metadata on assay ingestion

---

.pre-commit-config.yaml
.travis.yml
README.md
requirements.dev.txt

Analogous to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/153

Add pre-commit dependency and black pre-commit hook

---

functions/auth0.py

Currently, every log for which auth0 doesn't provide a user profile is showing up with `(USER_NAME=[none])`. This PR tries to provide better user name defaults based on log event type.

Add better messages when no user profile info is provided in auth0 logs

---

functions/patient_sample_update.py
functions/uploads.py
main.py

goes with https://github.com/CIMAC-CIDC/cidc-api-gae/pull/143

allows to run CFns in a local http mode for dev

---

functions/uploads.py
requirements.txt
tests/functions/test_uploads.py

Propogate changes from https://github.com/CIMAC-CIDC/cidc-api-gae/pull/185

Bump cidc-api-modules package version to support crc32c

---

functions/emails.py
functions/uploads.py
requirements.txt
tests/functions/test_emails.py

see also 
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/189
https://github.com/CIMAC-CIDC/cidc-schemas/pull/249

emails with attachments

---

functions/uploads.py

I was unable to come up with a test, and I'd appreciate help figuring it out

fix mixing artifact infos

---

functions/upload_postprocessing.py
functions/uploads.py
functions/visualizations.py
requirements.txt
tests/functions/test_upload_postprocessing.py
tests/functions/test_uploads.py
tests/functions/test_visualizations.py

changes accompanying https://github.com/CIMAC-CIDC/cidc-api-gae/pull/207/files

Use UploadJobs model instead of AssayUploads/ManifestUploads

---

functions/auth0.py

fix for 
```
File "/user_code/functions/auth0.py", line 99, in _get_last_auth0_log_id
last_blob = max(blobs, key=lambda b: b.name) if blobs else None
ValueError: max() arg is an empty sequence
```

fix auth0 log export for no last log entries

---

functions/settings.py
functions/uploads.py
tests/functions/test_uploads.py

based on https://github.com/CIMAC-CIDC/cidc-devops/pull/43

custom role for biofx access

---

functions/users.py
requirements.txt

goes with https://github.com/CIMAC-CIDC/cidc-api-gae/pull/261

report disabled_inactive_users

---

functions/upload_postprocessing.py
functions/uploads.py
requirements.txt
tests/functions/test_uploads.py

propagating changes from https://github.com/CIMAC-CIDC/cidc-api-gae/pull/282

Add facet group support

---

functions/visualizations.py
tests/functions/test_visualizations.py

Categories sorting for CG

---

functions/uploads.py
requirements.txt

Companion to:
https://github.com/CIMAC-CIDC/cidc-schemas/pull/393
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/347

Use prism.merge_artifacts

---

.github/workflows/ci.yml
README.md
functions/__init__.py
functions/users.py
main.py
requirements.txt
tests/functions/test_users.py

counterpart to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/369

Add daily function for refreshing GCS download perms

---

requirements.txt

see https://github.com/CIMAC-CIDC/cidc-api-gae/pull/433 and https://github.com/CIMAC-CIDC/cidc-schemas/pull/437

Bump for api for schemas

---

requirements.txt

[0.24.13 to 0.24.14](https://github.com/CIMAC-CIDC/cidc-api-gae/pull/436/files) and [schemas 0.24.14 to 0.24.15](https://github.com/CIMAC-CIDC/cidc-schemas/pull/437/files)
[0.24.14 to 0.24.15](https://github.com/CIMAC-CIDC/cidc-api-gae/pull/442/files)

Prod deploy for fixing cytof and pandas

---

functions/visualizations.py
requirements.txt
tests/functions/test_visualizations.py

accompaniment to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/446

Updates to support optional data_format's

---

.env
.env.prod.yaml
.env.staging.yaml
requirements.txt

corresponding API deploy: https://github.com/CIMAC-CIDC/cidc-api-gae/pull/476/files

IHC prod deploy

---

requirements.txt

after https://github.com/CIMAC-CIDC/cidc-api-gae/pull/510

Prod deploy for ATACseq support

---

requirements.txt

https://github.com/CIMAC-CIDC/cidc-api-gae/commit/ca425e0bddd65415548ef6d3d31befb2247fe505

CIDC-1142 api bump to allow for S1609 WES TWIST

---

requirements.txt

Discovered in testing. Incorrect call not checked by test mocking.
See also: https://github.com/CIMAC-CIDC/cidc-api-gae/pull/597

CIDC-1134 bump API for patch

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/613 and https://github.com/CIMAC-CIDC/cidc-schemas/pull/509 for [CIDC-1170](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1170) and [CIDC-1182](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1182) to unblock [CIDC-1135](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1135)

CIDC-1170 bump API for CSMS tweaks

---

requirements.txt

https://github.com/CIMAC-CIDC/cidc-schemas/pull/510
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/614

CIDC-1146 bump API for mIF tweak

---

requirements.txt

prod deploy

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/618

CIDC-1135 API bump for logging

---

requirements.txt

https://github.com/CIMAC-CIDC/cidc-schemas/pull/511
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/619

CIDC-1127 bump API version for mIF

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/623

CIDC-1135 bump API

---

functions/csms.py
tests/functions/test_csms.py

CIDC-1135 fix error in find-replace

---

functions/csms.py

CIDC-1135 add logging for all CSMS manifest flows

---

functions/csms.py

CIDC-1182 add match condition to exclude legacy manifests

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-schemas/pull/513 and accidental direct commit to `master` https://github.com/CIMAC-CIDC/cidc-api-gae/commit/29afa0cea906f812bff86dd1771061a18cfafc11
[CIDC-1194](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1194) to allow for documenting complexities involved in tumor-(patient normal), tumor-donor, and tumor-(combined normal) analyses.

CIDC-1194 bump API/schemas to add WES analysis pair-level comments

---

requirements.txt

Bump version for https://github.com/CIMAC-CIDC/cidc-schemas/pull/512, https://github.com/CIMAC-CIDC/cidc-api-gae/pull/631

CIDC-1191 bump api version

---

.github/workflows/ci.yml

Add CI for deploy of refresh download perms
Currently being associated with an incorrect pub/sub topic
Add new entry to CI.yml

CIDC-1187 1198 add CI for deploy of refresh download perms

---

.github/workflows/ci.yml

CIDC-1187 1198 lower timeout to allowed max

---

functions/grant_permissions.py
requirements.txt

https://github.com/CIMAC-CIDC/cidc-schemas/pull/514
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/643

CIDC-1207 bump API version

---

requirements.txt

https://github.com/CIMAC-CIDC/cidc-schemas/pull/515

CIDC-1217 bump

---

requirements.txt

https://github.com/CIMAC-CIDC/cidc-api-gae/pull/652

CIDC-1198 api bump for patch attempt

---

requirements.txt

API bump for
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/653

CIDC-1198 api bump for ACL-blocking bug fix

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/655

CIDC-1198 bump API for new storage client batching

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/656

CIDC-1198 bump for add error logging

---

functions/grant_permissions.py

CIDC-1198 mistake on which params were getting passed

---

functions/grant_permissions.py

CIDC-1198 fix misreferenced param

---

requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/659

CIDC-1198 bump API for bugfix

---

requirements.txt

API Version bump to deploy https://github.com/CIMAC-CIDC/cidc-schemas/pull/516

CIDC-1249 WES 10021 compatibility deploy

---

.github/workflows/ci.yml
functions/csms.py
functions/grant_permissions.py
functions/users.py
requirements.txt
tests/functions/test_csms.py

Tweak email messages for ACL and CSMS
Clarify what's going on, who should address it, and specified prod vs staging in the subject.

CIDC-1240 tweak email messages for ACL and CSMS

---

requirements.txt

CIDC-1124 Update requirements.txt

---

requirements.txt

CIDC-1124 patch the markup version

---

.github/workflows/ci.yml
CHANGELOG.md
requirements.txt

Parallels
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/680

CIDC-1301 Prod deploy for bug fix

---

CHANGELOG.md
requirements.txt

CIDC-1303 API version bump

---

CHANGELOG.md
requirements.dev.txt
requirements.txt

Fix werkzeug to try resolve deploy error
Last deployment threw `LocalStack object has no attribute __ident_func__` from within cidc_api in `master.py`
Werkzeug 2.1 removed a function depended on by the version of flask-sqlalchemy we're using
See https://stackoverflow.com/questions/71695691/flask-app-ctx-stack-ident-func-error-due-to-ident-func-deprecated-in-we

CIDC-1303 fix werkzeug to try resolve deploy error

---

.pre-commit-config.yaml
CHANGELOG.md
functions/users.py
functions/util.py
functions/visualizations.py
requirements.dev.txt
requirements.txt

Increase dependency versions.
To fix `click` incompatibilities.

Version bumps

---

CHANGELOG.md
requirements.txt

CIDC-1353 Bump API version for addition of Microbiome

---

CHANGELOG.md
requirements.txt

Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/697
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/530
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/531
- [CIDC-987](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-987)
- [CIDC-884](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-884)

CIDC-987 bump api

---

CHANGELOG.md
requirements.txt

Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/701
Deploys
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/356/files

CIDC-987 prod deploy to bump api 

---

CHANGELOG.md
requirements.txt

CIDC-1377 bump api version for new bait set

---

CHANGELOG.md
requirements.txt

CIDC-1382 bump API for schemas bump for hande req relaxation

---

CHANGELOG.md
requirements.txt

CIDC-1382 Pin flask version to fix issue with latest version

---

CHANGELOG.md
requirements.txt

CIDC-1421 bump API for schemas bump for hande manifest req relaxation

---

CHANGELOG.md
requirements.txt

CIDC-1421 Prod Deploy

---

CHANGELOG.md
requirements.txt

CIDC-1429 CIDC-1422 CIDC-1421 bump API version for fixes and changes

---

CHANGELOG.md
requirements.txt

bump API for microbiome metadata template changes and new shipping lab
version bump need to complete microbiome ingestion CIDC-1385
Standard process

CIDC-1385 bump API for microbiome metadata template changes

---

CHANGELOG.md
requirements.txt

bump API for microbiome metadata template changes and new shipping lab
Fixes for ingestion CIDC-1385
Standard Procedure

CIDC-1385 Prod deploy bump API for microbiome metadata template changes

---

CHANGELOG.md
requirements.txt

Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/731
Bump API to add prism encryption to new participant ids in our CSMS API
Current system causing emails with `MergeCollisionException('participant_id', '<encrypted>', '<unencrypted>')`

CIDC-1457 api bump

---

CHANGELOG.md
requirements.txt

Update API version for new version pin
resolve run error

CIDC-1486 update for new version pin

---

CHANGELOG.md
requirements.txt

API push for functionality fixing of bigquery permission delivery

CIDC-1486 API push for function fixing

---

CHANGELOG.md
requirements.txt

API version bump for project reference fix

CIDC-1486 API version bump for project reference fix

---

CHANGELOG.md
requirements.txt

API version bump for consolidation of microbiome and ctdna analysis files.
consolidate to follow CIDC precedent

CIDC-1502 CIDC-1503 API bump for fixes

---

CHANGELOG.md
requirements.txt

API version bump for consolidation of microbiome and ctdna analysis files.
consolidate to follow CIDC precedent

PROD-DEPLOY CIDC-1502 CIDC-1503 API bump for fixes

---

CHANGELOG.md
requirements.txt
tests/functions/test_uploads.py

Parallels
https://github.com/CIMAC-CIDC/cidc-schemas/pull/553
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/749
Bump API and so schemas to put new updates to bioinformatics pipeline integration onto staging.
- [CIDC-1507](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1507) WES integration
- [CIDC-1495](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1495) update script to generate monitor configs
- [CIDC-1508](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1508) RIMA integration
- [CIDC-1496](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1496) config generation -- update script which generates RIMA configs
- [CIDC-1497](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1497) ingestion sheet generation -- generate script to auto generate RIMA ingestion sheets
- …

CIDC-1507 CIDC-1508 API/Schemas bump: update BioFX Pipeline config/ingestion files

---

CHANGELOG.md
requirements.txt

Parallels
https://github.com/CIMAC-CIDC/cidc-schemas/pull/554
https://github.com/CIMAC-CIDC/cidc-schemas/pull/555
https://github.com/CIMAC-CIDC/cidc-schemas/pull/556
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/751
- Bump API for MIBI, olink, and WES analysis updates
[CIDC-1511](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1511)
[CIDC-1507](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1507)
[CIDC-1520](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1520)

CIDC-1511 api/schemas bump for MIBI, olink, wes fixes

---

CHANGELOG.md
requirements.txt

API/schemas bump for clinical count bug fix
Closes CIDC-1519

CIDC-1519 API/schemas bump for clinical count bug fix

---

CHANGELOG.md
requirements.txt

API/schemas bump for adding meta.csv to TCR config returns
streamlining tcr analysis config generation for transfer

CIDC-1505 API/schemas bump for adding meta.csv to TCR config returns

---

CHANGELOG.md
requirements.txt

Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/758
API bump: new front-page counting
[CIDC-1525](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1525) Correct the sample counts on Portal homepage

Count update

---

CHANGELOG.md
requirements.txt

API/schemas bump for adding batch to meta.csv for TCR

API/schemas bump for adding batch to meta.csv for TCR

---

CHANGELOG.md
requirements.txt

API/schemas bump for wes bait set swap

CIDC-1544 API/schemas bump for wes bait set swap

---

CHANGELOG.md
requirements.txt

API/schemas bump for dateparser version update

CIDC-1181 API/schemas bump for dateparser version update

---

CHANGELOG.md
requirements.txt

Parallels
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/571
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/777
API.Schemas bump for:
- Fix WES pipeline configuration -- errors with no tumor-only samples
- Add `Pass at Risk` option to `quality_of_sample` enum on shipping manifests
- [CIDC-1571](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1571) ABTC1603 WES - hit [error](https://console.cloud.google.com/logs/query;query=severity%3DERROR;cursorTimestamp=2022-12-08T21:32:10.628065Z?project=cidc-dfci) of "`NoneType` object is not iterable
-  WES pipeline config uses `get` from patch before iterating over runs; forgot to pass a default iterable and so returned `None` by default
- [CIDC-1572](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1572) 10104 WES (Batch 2) - has new …

CIDC-1571 CIDC-1572 api bump

---

CHANGELOG.md
requirements.txt

Parallels
- https://github.com/CIMAC-CIDC/cidc-ngs-pipeline-api/pull/65
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/572
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/779
API/Schemas bump to: 
- remove ATACseq analysis batch report, facets, and details
- lowercase buckets and instance names in biofx pipeline configs
- fix bug in `multifile` handling on the `upload_jobs` table, where it was set backwards
- [CIDC-1583](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1583) merge PR for atacseq_output_API.json - follow-up with schemas
- [CIDC-1587](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1587) Wes config/ingestion sheet generation -- make case match (make google bucket name all lowercase)
- [CIDC-1591](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1591) Bug fix - …

CIDC-1583 CIDC-1587 CIDC-1591: api/schemas bump

---

CHANGELOG.md
requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/781
API/Schemas bump to add `urine` to manifests' `type of sample`
[CIDC-1594](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1594) to unblock [CIDC-1590](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1590) olink upload for GU16-257

CIDC-1594 api schemas bump

---

CHANGELOG.md
requirements.txt

Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/783

CIDC-1588 API bump

---

CHANGELOG.md
functions/grant_permissions.py
requirements.txt

Deploys
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/428
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/429
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/430
- API bump to
- deduplicate blobs in revoke
- fix blob prefix generation error on uploads without files
- Fix error if no users or blobs to apply permissions to
[CIDC-1588](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1588)
- error on autodisable when overlapping prefixes were not deduplicated, causing collisions
- `KeyError` on manifests, which have no file prefix and so no entry in schemas prefix dict
- preemptively prevent more `KeyError`s that shouldn't be reachable
- use `.get()` on trial/upload `dict` in case of missing keys
- check user emails and blobs in case of empty lists
patched …

CIDC-1588 CIDC-1601 DEPLOY: permissions patches and fixes

---

CHANGELOG.md
functions/grant_permissions.py
requirements.txt
tests/functions/test_grant_permissions.py

Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/441
Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/800
Fix bug causing error on cloud issuing of cross-trial permissions
This is interaction with accepted param types from API, so would need integrative testing
Discovered in staging testing
Extend test to check param types for this function
Test here needs to be changed if the underlying API function changes
No need to bump API version, as all changes there are internal to API

Prod deploy: testing, fix type bug

---

CHANGELOG.md
requirements.txt

bump api/schemas for microbiome change to remove req for reverse index

CIDC-1703 bump api/schemas for microbiome change

---

CHANGELOG.md
requirements.txt

Parallels:
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/579
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/804
API/Schemas bump to:
1. Allow type string for DNA QC markers in normal blood/tissue and tumor tissue DNA manifests
2. Add Serum as valid processed_sample_type
1. For 10057 / TCR, DNA QC were not recorded, want to use a string N/A value to correct represent
2. For 2017-0349 / olink, were submitted as first batch of serum samples

CIDC-1713 CIDC-1714 api/schemas bump

---

CHANGELOG.md
requirements.txt

Parallels: https://github.com/CIMAC-CIDC/cidc-api-gae/pull/805
Deploys: https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/446
API/Schemas bump to:
1. Allow type string for DNA QC markers in normal blood/tissue and tumor tissue DNA manifests
2. Add Serum as valid processed_sample_type
1. For 10057 / TCR, DNA QC were not recorded, want to use a string N/A value to correct represent
2. For 2017-0349 / olink, were submitted as first batch of serum samples

CIDC-1713 CIDC-1714 PROD DEPLOY api/schemas bump

---

CHANGELOG.md
requirements.txt

- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/813 

API bump for CIDC_MAILING_LIST

---

CHANGELOG.md
requirements.txt

Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/450

PROD DEPLOY: API bump for CIDC_MAILING_LIST
