CIMAC-CIDC/cidc-cloud-functions

- .env
- .gitignore
- .travis.yml
- functions/settings.py
- functions/uploads.py
- functions/util.py
- requirements.txt
- tests/conftest.py
- tests/functions/test_uploads.py
- tests/util.py
This PR implements SQLAlchemy session sharing across cloud functions. Also, adds a database lookup and dry-run output to the `uploads.ingest_upload` function.
~TODO: run migrations on the test database before running the tests.~ Instead, mocking database functionality for now rather that modifying the database in tests.
> Connect to the database from cloud functions

- .travis.yml
- README.md
- functions/__init__.py
- functions/emails.py
- functions/settings.py
- functions/uploads.py
- main.py
- requirements.txt
- tests/functions/test_emails.py
Adds a new cloud function, `functions.emails.send_email`, that sends an email published to the Pub/Sub `emails` topic using the SendGrid API.
> SendGrid email sender

- .env.prod.yaml
- .env.staging.yaml
- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
Now, `ingest_upload` adds GCS object URLs to assay metadata and merges that updated metadata into the existing assay metadata object for that trial using `TrialMetadata.patch_trial_metadata`.
> Add GCS object URLs and merge assay metadata in ingest_upload

- requirements.txt
...one reason why using the API rather than access the database directly might be favorable.
> Bump cidc-api-modules version

- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
Use https://github.com/CIMAC-CIDC/cidc-api-gae/pull/42 to save metadata for ingested files to the `downloadable_files` table.
> Save file metadata to downloadable_files table

- functions/uploads.py
- functions/util.py
- tests/conftest.py
- tests/functions/test_uploads.py
- tests/functions/test_util.py
Hot fix: under certain circumstances, if a database transaction in a previous function invocation fails, the postgres error from that previous invocation might get thrown during the current invocation (even though it is unrelated). ~Rolling back the database session before using it flushes such errors, and prevents this from happening.~
**Update**: per @curlup's comment, this PR updated `get_db_session` to share a global sqlalchemy engine instance, but create a new session for every invocation of `get_db_session`.
> Share sqlalchemy engine, not session, across function invocations

- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
It breaks because it needs to be up to date with a corresponding api version - https://github.com/CIMAC-CIDC/cidc-api-gae/pull/62 
Don't now how to do that w/o api release.
> Prism calls removed (moved to api code), upload/target gcs uri formatting moved to api

- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
Changes related to https://github.com/CIMAC-CIDC/cidc-api-gae/pull/95.
On `ingest_upload` success/failure, update the corresponding upload job's `status` and `status_details` fields appropriately.
Note: this is going to fail to build until `cidc-api-modules==0.5.0` is actually deployed once https://github.com/CIMAC-CIDC/cidc-api-gae/pull/95 is merged.
> Write assay upload merge status to the database

- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
Update the `ingest_uploads` cloud function to make assay metadata files downloadable.
Note: build will fail until https://github.com/CIMAC-CIDC/cidc-api-gae/pull/97 is deployed.
> Downloadable assay metadata

- functions/uploads.py
Turns out you need to use the `get_blob` method to actually load object metadata like file size.
This is leading to null-related errors from SQLAlchemy when `DownloadableFiles.create_from_blob` is called.
> Load blob metadata from GCS

- functions/uploads.py
An artifact's upload timestamp should reflect when it was uploaded to the upload bucket, not transferred to the data bucket.
> Store original upload time in artifact info

- .env
- functions/uploads.py
- requirements.txt
- tests/functions/test_uploads.py
Use the interface defined in https://github.com/CIMAC-CIDC/cidc-api-gae/pull/161 to send an email when assay ingestion succeeds.
> Send email alert on assay upload success

- functions/uploads.py
Now, `assay_uploads.assay_patch` will represent the full patch that is actually applied to the corresponding `trial_metadata` object. Currently `assay_uploads.assay_patch` only contains upload placeholder UUIDs for the artifacts.
> Save metadata patch with artifact info to assay upload job

- .travis.yml
- deploy/pubsub.sh
- functions/uploads.py
- tests/functions/test_uploads.py
This PR aims to do so in two ways:
* by increasing the allowed runtime of the `ingest_upload` cloud function to 2 minutes (and the memory limit to 512MB)
* by parallelizing the GCS blob copy step of the function
> Prevent ingest_upload timeouts

- .travis.yml
- functions/auth0.py
- tests/functions/test_auth0.py
This PR fixes a couple issues with the existing Auth0 log ingestion cloud function by:
* making the function adhere to the Auth0 free tier rate limit of 2 requests per second
* batching the write to stackdriver rather than writing line-by-line (this was causing timeouts occasionally)
* naming the GCS objects to which logs are saved based on the dates in the logs themselves, not the date on which the function is run
> Auth0 rate limiting, stackdriver batching, and date-handling fixes

- .env.prod.yaml
- .env.staging.yaml
This fixes the bug that caused us to get emails saying data was uploaded to staging when it was actually uploaded to prod. We weren't setting `ENV` appropriately in cloud functions, and `cidc_api.config.settings.ENV` defaults to `"staging"` (we don't actually want this default, so up next will be a PR removing that default from the API here https://github.com/CIMAC-CIDC/cidc-api-gae/blob/b24b388d1c4224d87fdb9576dec550d4bde3527b/cidc_api/config/settings.py#L15).
> Add missing ENV environment variable to staging and prod configs

- functions/upload_postprocessing.py
This was preventing all derivative files from getting published (e.g., participant and sample CSVs after manifest upload).
> Fix create_from_blob kwarg typo in _derive_files_from_upload

- .travis.yml
- README.md
- functions/users.py
- requirements.txt
- tests/functions/test_users.py
Accompaniment for https://github.com/CIMAC-CIDC/cidc-api-gae/pull/249
Adds the `disable_inactive_users` function, triggered by the `daily_cron` pubsub topic.
> Add disable_inactive_users function

- .env
- functions/uploads.py
This PR improves the `ingest_upload` function in two ways:
* decreases memory requirements by sharing one GCS client across calls to cloud storage, rather than instantiating a new client for every GCS operation.
* improves performance by taking advantage of a couple additional opportunities for multithreading on IO-bound operations.
Some initial experimentation suggests that all of the `print` statements in the `ingest_upload` function may also be slowing it down, so I'm going to leave this PR as a draft while I consider alternatives. The biggest performance hit we take is on artifact metadata merging, though, which is a product of inefficiency in `prism`'s implementation.
> Share one GCS client; introduce more multithreading

- functions/settings.py
- functions/uploads.py
- functions/util.py
Was checking FLASK_ENV for development instead of ENV for dev like other repos
That surfaced a datetime vs datetime.datetime bug, and need to handle None return when not publishing
> FLASK_ENV -> ENV; handle bugs for ENV=dev

- functions/uploads.py
- tests/functions/test_uploads.py
This should at least remove any doubt as to whether shared `storage.Client` instances are the source of our Google auth errors, and at best actually fix the auth errors.
> Remove global GCS storage client from uploads.py

- functions/uploads.py
- tests/functions/test_uploads.py
Fixes a bug where many duplicate conditional IAM bindings were created for the same GCS prefix. The code is more or less copied from `cidc_api.shared.gcloud_client` (https://github.com/CIMAC-CIDC/cidc-api-gae/blob/5701210f10e77583c2bebe840e10a2d0d8ff51d2/cidc_api/shared/gcloud_client.py#L339), but slight differences for this use case would've required modifying the `gcloud_client` code. Preventing interdependency seemed like the lesser of two evils.
> Prevent duplicate biofx analysis group iam bindings

- functions/uploads.py
Generally speaking, Python multithreading is provides a performance benefit only on operations involving I/O. Since these calls to `DownloadableFiles.create_from_metadata` don't actually write out to the database, there's no reason to multithread them (all records are created in a single transaction when `session.commit()` is called towards the end of this function).
> Don't multithread DownloadableFiles.create_from_metadata calls

- requirements.txt
Adds a controls section for TCRseq assay, as well as a sheet on tcr_adaptive assay template as well.  
Extends [CIDC-1130](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1130) because I missed this last time.  
See https://github.com/CIMAC-CIDC/cidc-schemas/pull/500 and https://github.com/CIMAC-CIDC/cidc-api-gae/pull/577
> CIDC-1130 api/schemas bump for TCRseq controls

- functions/csms.py
- main.py
- tests/functions/test_csms.py
Update event data format to use stringified python dict for matching the trial and manifest IDs when doing CSMS change detection.
Discovered in testing. Old implementation used url-style param strings but did not include the required character escaping and so failed when the manifest ID contains an `&`, which is quite common in eg H&E.
Instead, this uses the result of `str` of a python `dict` containing the values which is then reparsed via `dict(eval(<data>))` within the function to regenerate the exact input.
* Any failures in unpacking continue to do a dry-run against all manifests (with a warning)
* Correctly unpacked data that doesn't contain both trial and manifest ID continue to throw an Exception
* Despite the usual concerns around using `eval`, this is believed to be safe here as …
> CIDC-1134 update CSMS event data format to use dict

- functions/csms.py
- functions/settings.py
- tests/functions/test_csms.py
Add Google secret to pass to uploader_email in CSMS pseudo-upload.
[CIDC-1135](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1135) causes fk error on `uploader_email=''`
Added to staging secrets and mocked in tests
> CIDC-1135 add secret to pass to uploader_email

- functions/csms.py
- requirements.txt
- tests/functions/test_csms.py
Catch errors in inserting a new manifest as well
[This testing example](https://console.cloud.google.com/logs/query;query=resource.labels.function_name%3D%22update_cidc_from_csms%22%0Alabels.execution_id%3D%22m1umfjcjeppp%22;timeRange=PT3H;cursorTimestamp=2021-11-19T21:52:47.038Z?project=cidc-dfci-staging) didn't generate an email.
Use nested `try...catch...else` for errors while catching inside `NewManifestError`
Added test to prevent reversion.
> CIDC-1134 catch errors in inserting a new manifest as well

- functions/csms.py
- requirements.txt
- tests/functions/test_csms.py
Use new explicit variable for dry_run for better error checking when not actually inserting, facilitated by https://github.com/CIMAC-CIDC/cidc-api-gae/pull/629 .
Currently, dry_run of CSMS sync in cloud functions doesn't actually check any of the db values, so mainly errors caught by [models/templates/csms_api.py::_initial_manifest_validation](https://github.com/CIMAC-CIDC/cidc-api-gae/blob/csms-dry_run/cidc_api/models/templates/csms_api.py#L748) were being checked in [models/templates/csms_api.py::detect_manifest_changes](https://github.com/CIMAC-CIDC/cidc-api-gae/blob/csms-dry_run/cidc_api/models/templates/csms_api.py#L954).  
This allows for an explicit check and rollback call from the cloud function to both `insert_manifest_from_json` and `insert_manifest_into_blob`.
- Use default …
> CIDC-1135 use new dry_run variable for better error checking when not actually inserting

- .github/pull_request_template.md
- functions/csms.py
- functions/settings.py
- requirements.txt
- tests/functions/test_csms.py
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/630
CSMS:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/290 https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/291 API bumps
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/292 add INTERNAL_USER_EMAIL secret
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/293 bug fixes
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/294 logging
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/295 https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/296 https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/297 API bumps
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/298 ignore excluded manifests
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/299 catch errors when …
> Prod deploy for notes in WES paired analysis, CSMS functionality

- .env
- .env.prod.yaml
- .env.staging.yaml
- functions/__init__.py
- functions/grant_permissions.py
- main.py
- requirements.txt
- tests/functions/test_grant_permissions.py
REQUIRES `grant_download_perms` pubsub channel to be created on staging project before merging.
Add function to trigger API's Permissions.grant_all_download_permissions
Parallels and supports https://github.com/CIMAC-CIDC/cidc-api-gae/pull/642
Currently, running over the 10mins that API times out at -- cloud functions can have a much longer time out that's under our control.
single call to API's `Permissions.grant_all_download_permissions` function
May still be too slow, next idea is to include trial / upload matching to run in smaller batches.
> CIDC-1187 1198 add CFn to grant all download permissions

- functions/grant_permissions.py
- requirements.txt
- tests/functions/test_grant_permissions.py
Add optional `trial_id` kwarg from message data to `grant_all_download_permissions` to get around Google CFn timeouts from trying to do all the files in one go.
Copied message parsing code from CSMS function
Pass as kwarg to `cidc_api.models.models.Permissions.grant_all_download_permissions` as added
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/651
Still might need to be broken down further.
> CIDC-1198 add trial_id input to grant_all_download_permissions

- functions/__init__.py
- functions/grant_permissions.py
- main.py
- requirements.txt
- tests/functions/test_grant_permissions.py
Parallels
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/654
Add assay filter to grant "all" download perms
Keep the cloud function name itself as `grant_all_download_permissions`  for now
- Changed `\*_all_download_permissions to `\*_download_permissions`
- CFn name itself remains `grant_all_download_permissions`  but all code and functions lose the `_all`
- use new `upload_type` kwarg on `cidc_api.models.Permissions.grant_download_permissions`
Still might be too long -- next idea is to find some sort of paging within the assay type, possibly by having a CFn to grant for a particular set of files that can be automatically …
> CIDC-1198 add assay filter to grant "all" download perms

- .github/workflows/ci.yml
Correctly point to renamed `grant_download_permissions` function in CI
I misunderstood what the name in the CI configuration was referencing -- it's the name of the function in `main.py`.
> CIDC-1198 CI name fix

- functions/grant_permissions.py
- functions/worker.py
- requirements.txt
- tests/functions/test_grant_permissions.py
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/658
Extend grant download permissions CFn functionality to handled all permissions operations.
Supports https://github.com/CIMAC-CIDC/cidc-api-gae/pull/658 's revoking permissions and cross trial/upload
- add revoke kwarg to both grant permissions function and permission worker
- allow for passing None for trial or upload type; already handled and widely used in the API
- add user_email_list to allowed for more targeted scopes
- update tests to match
- add a bunch of documentation
While list_blobs for cross trial / upload types could time out, direct local CLI testing with staging indicates it should be fine.
> CIDC-1198 add revoke, user_email_list, docs, None handling

- functions/users.py
- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/660
Sends email when users are disabled for inactivity
> CIDC-1235 bump API version, send email of disabled emails

- CHANGELOG.md
- functions/grant_permissions.py
- functions/uploads.py
- requirements.txt
- tests/functions/test_grant_permissions.py
- tests/functions/test_uploads.py
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/664
- Fix handling of subcases when applying permissions to multiple sets of files
- Add flag for group email for BioFX group
Discovered in initial ACL deployment and reapplying broad permissions.
- BioFX group is throwing errors because it's being treated as a user
- Need to know which users are to be applied to each trial / upload combo when applying broad permissions
- Add optional `is_group: bool` flag to the messages for `grant_download_permissions`, pass through to `permissions_worker`, and pass to API's `[grant/revoke]_download_access_to_blob_names`
- If a `user_email_list` is not provided, load from the database using API's new `models.models.Permissions.get_user_emails_for_trial_upload`
- returns structure with all user …
> CIDC-1240 improve ACL handling for edge cases

- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/667
API bump to fix a mistake where permissions for being applied for disabled users.
API won't return the emails of users who are disabled.
Doesn't stop you from adding / revoking permissions to other users by supplying them in the `user_email_list`
> CIDC-1240 ACL bump to not apply permissions for disabled users

- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/671
Change alert email to new group cidc-alert@ds.dfci.harvard.edu instead of cidc@jimmy.harvard.edu which is administered by DFCI DS.
[CIDC-1252](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1252)
Added long comments in API on what emails are sent both there and from here using the API `send_email` function to the `CIDC_MAILING_LIST`, both from `shared.emails`.
> CIDC-1252 API bump to change mailing list address

- CHANGELOG.md
- requirements.txt
Bump API dependency to bump `schemas` dependency to peg version for `regex` library to prevent errors in date format validation.
`regex==2022.3.15` throws `bad escape \d at position` when validating dates in manifest uploads
Peg to last known working version.
> CIDC-1301 api bump

- CHANGELOG.md
- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-schemas/pull/524 and https://github.com/CIMAC-CIDC/cidc-api-gae/pull/691
Bump API to bump schemas to add ctDNA for assay_type in blood manifests
- [CIDC-1339](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1339) Add ctDNA to manifest assay_type options
> CIDC-1339 bump api

- CHANGELOG.md
- requirements.txt
Parallels:
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/528
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/693
Add support for ctDNA assay and ctDNA analysis
[CIDC-1355](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1355) ctDNA support - template and DM, bump
- bump API to version with updated schemas and ctDNA analysis counting
Don't have first CIDC dataset for true test upload on staging yet.
> CIDC-1355 bump api for new ctdna

- CHANGELOG.md
- requirements.txt
Parallels:
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/543
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/722
- https://github.com/CIMAC-CIDC/cidc-ui/pull/452
Bump API version
- [CIDC-1424](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1424) Make changes to portal access provider to simplify enabling clinical data access
> CIDC-1424 bump api for cross-assay perms not include clinical

- CHANGELOG.md
- functions/upload_postprocessing.py
- requirements.txt
- tests/functions/test_upload_postprocessing.py
Fix bug putting wrong upload_type on derived files
[CIDC-1425](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1425) Fix Olink Study Wide file download
derived files were given an incorrect upload_type and so were not able to be downloaded through the API due to upload type-based permission checks
> CIDC-1425 bugfix deploy

- CHANGELOG.md
- functions/csms.py
- requirements.txt
- tests/functions/test_csms.py
Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/730
- API bump for removing relational db code
- Update CSMS function to match
[CIDC-1457](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1457) Remove relational db code elements
for simplification and clarity
> CIDC-1457 remove relational components

- CHANGELOG.md
- functions/csms.py
- requirements.txt
Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/733
Bump API to add a role for PACT users that is equivalent to the Network viewer role.
- [CIDC-1484](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1484) Add PACT User Type
- 
> CIDC-1484 API bump to add pact user role

- CHANGELOG.md
- functions/csms.py
- requirements.txt
- tests/functions/test_csms.py
Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/386
Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/734
Bump API to add a role for PACT users that is equivalent to the Network viewer role.
- [CIDC-1484](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1484) Add PACT User Type
> CIDC-1484 Prod deploy: API bump to add pact user role

- CHANGELOG.md
- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/735
A user informed CIDC that they did not have the correct access, leading to discovery that new uploads did not apply the correct permissions. Code to separate clinical data from cross-assay permissions introduced error in API.
- [CIDC-1490](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1490) Fix bug in permissions on new uploads
> CIDC-1490 api bump for bug fix for permissions on new uploads

- CHANGELOG.md
- functions/csms.py
- requirements.txt
Deploys https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/388
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/736
A user informed CIDC that they did not have the correct access, leading to discovery that new uploads did not apply the correct permissions. Code to separate clinical data from cross-assay permissions introduced error in API.
- [CIDC-1490](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1490) Fix bug in permissions on new uploads
> CIDC-1490 deploy of api bump for bug fix for permissions on new uploads

- CHANGELOG.md
- requirements.txt
Parallels:
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/551
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/737
Implement support for MIBI assay with 4 files as provided in examples from Sricharan at Standford.
- [CIDC-1481](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1481)
- 3 example datasets all followed the same format.
- Further metadata is stored in the OME.TIFF headers
No real network data to ensure their adherence to this structure
> CIDC-1481 api bump to add MIBI support

- CHANGELOG.md
- requirements.txt
Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/738
Temporarily swap out the staging uploader role until we can remake the `objectUploader` which is accidentally permanently deleting.
To test MIBI upload on staging
API bump
No tests
> CIDC-1482 API bump to unblock staging uploads with Uploader Role swap

- CHANGELOG.md
- functions/csms.py
- requirements.txt
Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/390
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/391
Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/740
Implement support for MIBI assay with 4 files as provided in examples from Sricharan at Standford.
- [CIDC-1481](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1481)
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/391 is just for staging to unblock testing
- 3 example datasets all followed the same format.
- Further metadata is stored in the OME.TIFF headers
No real network data to ensure their adherence to this structure
> CIDC-1483 prod deploy of api bump to add MIBI support 

- CHANGELOG.md
- functions/users.py
- requirements.txt
- tests/functions/test_users.py
Updates for bigquery permission delivery, adds bigquery to permission refresh.
Enables user access to data exploration.
> CIDC-1486 add bigquery to permission refresh

- CHANGELOG.md
- functions/users.py
- requirements.txt
- tests/functions/test_users.py
fix call to Permissions.grant_user_permissions from Permissions.grant_iam_permissions
API version push
API call not updated for permission update
> CIDC-1486 fix function call for permission update

- CHANGELOG.md
- functions/users.py
- tests/functions/test_uploads.py
- tests/functions/test_users.py
Changed user permission refresh to just reissue upload access for active users
[CIDC-1500](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1500) Update permissions refresh in CFn -- likely cause of late night permissions error emails
As object lister IAM permissions and ACL-based download permissions don't expire, those do not need to be refreshed. The only remaining call in the target function was passing through to `cidc_api.shared.gcloud_client/refresh_intake_access`
No way to test if this will resolve permissionsissues
> CIDC-1500 minimize user perms refreshed

- CHANGELOG.md
- functions/users.py
- requirements.txt
- tests/functions/test_users.py
- API bump for https://github.com/CIMAC-CIDC/cidc-api-gae/pull/755
- On permissions refresh, update active user filter to require users are both not disabled and approved
[CIDC-1524](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1524) Permissions refresh in CFn -- giving bigquery to ALL users regardless of approval
Add additional filter clauses.
- `!= None` syntax from [here](https://stackoverflow.com/questions/21784851/sqlalchemy-is-not-null-select)
- `Users.disabled == False` as in API `models/models.py`
> CIDC-1524 tighter BQ perms on refresh

- CHANGELOG.md
- functions/users.py
- requirements.txt
- tests/functions/test_uploads.py
- tests/functions/test_users.py
Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/406
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/407
- Changed user permission refresh to just reissue upload access for active users
- On permissions refresh, update active user filter to require users are both not disabled and approved
- [CIDC-1500](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1500) Update permissions refresh in CFn -- likely cause of late night permissions error emails
- [CIDC-1524](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1524) Permissions refresh in CFn -- giving bigquery to ALL users regardless of approval
- As object lister IAM permissions and ACL-based download permissions don't expire, those do not need to be refreshed. The only remaining call in the target function …
> CIDC-1500 deploy: updates to user permissions refreshment overnight

- CHANGELOG.md
- functions/upload_postprocessing.py
- functions/util.py
- requirements.txt
- tests/functions/test_upload_postprocessing.py
- API/schemas bump to change file derivation to return None instead of erroring when not defined
- handle null return and gracefully exit
- [CIDC-876](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-876) derive_files_from_... cloud functions throw errors when no derivation is implemented
if returned None, print note and exit successfully
> CIDC-876 change file derivation: don't error when not defined

- CHANGELOG.md
- requirements.txt
Parallels
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/568
API/Schemas bump to remove `analysis` from end of WES analysis folder in autogenerated templates
[CIDC-1552](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1552)
> CIDC-1552 api/schemas bump: remove analysis from wes folder

- .env
- .env.prod.yaml
- .env.staging.yaml
- CHANGELOG.md
- functions/grant_permissions.py
- functions/settings.py
- functions/uploads.py
- requirements.txt
- tests/functions/test_grant_permissions.py
- tests/functions/test_uploads.py
Remove separate permissioning system for biofx groups in ingest_upload.
Also remove unused `is_group` option in granting permissions functions, as it was only used by the above.
API bump for related removal of `is_group` option in granting/revoking permissions functions in the API, as it was only used by the above.
- separate from main permissions system in API
- making concurrent updates to the same files via grant_download_permissions_for_upload_job leading to dev alert email
- [CIDC-1554](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1554) Check in dev alerts for permissions and what is triggering them
Remove permissioning code and related constant pulled from the environment.
Remove `is_group` option and related code from `grant_download_permissions` and `permissions_worker`.
API …
> CIDC-1554 remove separate biofx permissioning

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
- tests/functions/test_grant_permissions.py
Parallels
- https://github.com/CIMAC-CIDC/cidc-schemas/pull/570
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/773
API/schemas bump for updated permissions handling
Changed download permissions handling to accept list of `upload_type`s
[CIDC-1554](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1554) Check in dev alerts for permissions and what is triggering them
When two individual assay permissions for same trial share a prefix, tries to update same file twice at the same time on dis/en-activate.
- Also allow `List[str]` instead of just `Optional[str]` for `upload_type` in target functions
- Convert blob names from `set` to `list` for chunking
Please include and complete the following checklist. You can mark an item as …
> CIDC-1554 allow list of uploads

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
- tests/functions/test_grant_permissions.py
Deploys
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/420
Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/775
API/schemas bump for updated permissions handling
Changed download permissions handling to accept list of `upload_type`s
[CIDC-1554](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1554) Check in dev alerts for permissions and what is triggering them
When two individual assay permissions for same trial share a prefix, tries to update same file twice at the same time on dis/en-activate.
- Also allow `List[str]` instead of just `Optional[str]` for `upload_type` in target functions
- Convert blob names from `set` to `list` for chunking
Please include and complete the following checklist. You can …
> CIDC-1554 PROD DEPLOY: allow list of uploads

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
Parallels https://github.com/CIMAC-CIDC/cidc-api-gae/pull/782
- API bump to
- deduplicate blobs in revoke
- fix blob prefix generation error on uploads without files
- Fix error if no users or blobs to apply permissions to
[CIDC-1588](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1588)
- error on autodisable when overlapping prefixes were not deduplicated, causing collisions
- `KeyError` on manifests, which have no file prefix and so no entry in schemas prefix dict
- preemptively prevent more `KeyError`s that shouldn't be reachable
- use `.get()` on trial/upload `dict` in case of missing keys
- check user emails and blobs in case of empty lists
these errors should NOT be reachable
Please include and complete the following checklist. You can mark an item as complete with the `- [x]` …
> CIDC-1588 api bump, safe emails/blobs

- CHANGELOG.md
- functions/grant_permissions.py
- functions/upload_postprocessing.py
- requirements.txt
- `changed` API bump for permission triggering for participants and samples info on upload
- `fixed` when ingesting derived manifest files mark upload type correctly
Manifest derived file permissions were not getting delivered correctly
If manifest derived files (participants or samples info) files are being added to database correctly mark upload type
> CIDC-1608 manifest permission fixes

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
- tests/functions/test_grant_permissions.py
changed API bump for permission triggering for participants and samples info on upload
fixed when ingesting derived manifest files mark upload type correctly
Manifest derived file permissions were not getting delivered correctly
If manifest derived files (participants or samples info) files are being added to database correctly mark upload type
added triggering for permissions on manifest upload
> CIDC-1608 Prod Deploy

- CHANGELOG.md
- requirements.txt
Bump API for permissions tweak
Recent extra calls to permission granting on manifests have caused demo alert triggers, so removal of any unneeded calls will hopefully prevent this
Only call upload_type permission grants on non-manifest uploads. Don't do any permission delivery on tumor_only_pairing ingestion
> CIDC-1619 bump API for perm tweak

- CHANGELOG.md
- functions/grant_permissions.py
Remove sending of dev alert email on permissions error
They haven't been too useful
Comment out
Still marked in the logs
> Remove dev alert email on permissions error

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/795
- API bug: Fix permission error where cross-assay single-trial permissions weren't granted/revoked on user (de)activate
- Better typing and variable handling in `grant_permissions` function for clarity in future maintenance
Discovered in testing related to [CIDC-1637](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1637) Clean up production resources and test
- API bump
- Use separate variables when converting user input to a new type eg `raw_data` and `raw_upload_type`
- Add clearer typing hints
> CIDC-1637 bump to fix cross-assay perms bug, clean up permissions function

- CHANGELOG.md
- functions/grant_permissions.py
- requirements.txt
Parallels:
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/796
Deploys:
- https://github.com/CIMAC-CIDC/cidc-cloud-functions/pull/439
Parallels
- https://github.com/CIMAC-CIDC/cidc-api-gae/pull/795
- API bug: Fix permission error where cross-assay single-trial permissions weren't granted/revoked on user (de)activate
- Better typing and variable handling in `grant_permissions` function for clarity in future maintenance
Discovered in testing related to [CIDC-1637](https://dfcijira.dfci.harvard.edu:8443/browse/CIDC-1637) Clean up production resources and test
- API bump
- Use separate variables when converting user input to a new type eg `raw_data` and `raw_upload_type`
- Add clearer typing hints
Please include and complete the following checklist. You can mark an item as complete with the …
> CIDC-1637 DEPLOY bump to fix cross-assay perms bug, clean up permissions function
